---
- name: Example ruleset 1
  hosts: all
  sources:
    - name: Source 1
      ansible.eda.url_check:
        urls:
          - https://example.com/heartbeat/
        delay: 10

  rules:
    - name: Rule 1
      condition: event.status == "down"
      action:
        run_job_template:
          name: "Reload server"
          organization: "Default"

- name: Example ruleset 2
  hosts: database
  sources:
    - name: PG Status
      ansible.eda.webhook:
        host: https://source.example.com/api/webhook/
        port: 443
        keyfile: /path/to/keyfile

  rules:
    - name: Rule 2
      conditinon:
        any:
          - event.payload.connections_free <= 10
          - event.payload.mem_free < 2048
      action:
        run_job_template:
          name: "Restart PostgreSQL server"
          organization: "Default"